#!/bin/sh

sudo rm /usr/bin/JK_PasswordManager 

run="#!/bin/sh

cd /usr/share/JK_PasswordManager || echo 'failed to run, try to reinstall'
./JK_PasswordManager
"

echo "$run" | sudo tee -a /usr/bin/JK_PasswordManager
sudo chmod +x /usr/bin/JK_PasswordManager

